"""added submission_date attribute to cover

Revision ID: 3e9e5200dc1a
Revises: b3e8b050e01d
Create Date: 2020-10-12 14:37:22.888487

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e9e5200dc1a'
down_revision = 'b3e8b050e01d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cover', schema=None) as batch_op:
        batch_op.add_column(sa.Column('submission_date', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cover', schema=None) as batch_op:
        batch_op.drop_column('submission_date')

    # ### end Alembic commands ###
